### ISSUE TITLE
/cli/check_moodle script has Windows-style line endings

### ISSUE THREAD

**Issue by pauln** [micaherne/moodle-local_nagios#4]
The /cli/check_moodle script has Windows-style line endings, which results in the following error:
`-bash: ./check_moodle: /usr/bin/php^M: bad interpreter: No such file or directory`

I don't have a Windows development environment to test on, so I'm not sure if a similar issue arises on Windows systems if the file contains Unix-style line endings... if it does, perhaps we need two versions of this wrapper script?

**Comment by micaherne** [comment]
Windows is usually fine with Unix-style endings,  so I'll get them fixed. Thanks for pointing it out!

**Comment by micaherne** [comment]
Hmm, I'm not able to reproduce this. On my Windows machine the file definitely has Unix line endings, and I thought it was maybe to do with git's core.autocrlf setting but I'm not convinced. I cloned the repo on a Linux box and opened the file in vi, which usually shows the ^M characters, but I'm not seeing them.

Would you mind cloning the repo again and checking that you're still seeing this?

**Comment by pauln** [comment]
Sorry - my mistake, it seems to have been caused by the combination of Windows and RHEL in my development environment (I run a RHEL VM on a Windows host, with the webroot shared between them).  A clean checkout directly on the RHEL side seems to have resulted in Unix-style endings.  I'll have to see if I can reconfigure the Windows side to stop it changing the line endings.

**Comment by micaherne** [comment]
That's a relief! Thanks for checking it out.
